name: seo_web

version: 1.0.0+2

publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter    
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.3
  auto_route: ^6.1.0
  flutter_bloc: ^8.1.2
  regexed_validator: ^2.0.0+1
  dio: ^5.0.0
  equatable: ^2.0.5
  provider: ^6.0.5
  json_annotation: ^4.8.1
  decimal: ^2.3.3
  flutter_secure_storage: ^9.0.0
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  uuid: ^4.3.1
  intl_utils: ^2.8.5
  logging: ^1.2.0
  flutter_svg: ^2.0.9
  tele_web_app:
    git: https://github.com/yeikel16/tele_web_app.git
  mockito: ^5.4.4

dependency_overrides:
  meta: ^1.11.0
  

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^6.1.0
  flutter_launcher_icons: "^0.13.0"
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  elementary_test: ^2.0.0




flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: BottomBarIcons
      fonts:
        - asset: fonts/BottomBarIcons.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic

