name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
     
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.8"
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get

      - name: Start unit test
        run: flutter test

      - name: Start integration test
        run: flutter test integration_test

      - name: Start release bundle build
        run: flutter build appbundle
        
      - name: Start release apk build
        run: flutter build apk --release
